### ISSUE TITLE
Exception in case registry values not installed during installation of R

### ISSUE THREAD

**Issue by jochenvanwylick** [jmp75/rdotnet#19]
When installing R without checking the option to save the R version in the registry, `REngine.GetInstance("path here")` fails with exception message:

> Windows Registry key 'SOFTWARE\R-core' not found in HKEY_LOCAL_MACHINE nor HKEY_CURRENT_USER

Stacktrace:

>   at RDotNet.NativeLibrary.NativeUtility.GetRCoreRegistryKeyWin32()
>   at RDotNet.NativeLibrary.NativeUtility.FindRHome(String rPath)
>   at RDotNet.NativeLibrary.NativeUtility.SetEnvironmentVariables(String rPath, String rHome)
>   at RDotNet.REngine.SetEnvironmentVariables(String rPath, String rHome)
>   at RDotNet.REngine.GetInstance(String dll, Boolean initialize, StartupParameter parameter, ICharacterDevice device)

This key seems to be used for determining the R location and the R version. In case neither are provided in GetInstance - I can imagine why the exception needs to be thrown.

However - I've provided the DLL file location in `GetInstance`. Then probably it's not necessary if the registry key cannot be found - so that the R version couldn't be determined, right?

**Comment by jochenvanwylick** [comment]
Oops - never mind `REngine.SetEnvironmentVariables()` solved my problem.
