### ISSUE TITLE
System.UInt64 support

### ISSUE THREAD

**Issue by hh1985** [jmp75/rdotnet#31]
Hi, 
When I was using RClr and got following error:
```
> clrGetMemberSignature(spec_obj, 'defaultArrayLength')
[1] "Property defaultArrayLength, UInt64, can write: True"
> clrGet(spec_obj, 'defaultArrayLength')
Error in (function ()  : 
  clr_obj_ms_convert_to_SEXP: COM variant type code 21 unsupported. Returning NULL
Error in clrCallStatic(clrFacadeTypeName, "GetFieldOrProperty", objOrType,  : 
  Type:    RDotNet.EvaluationException
Message: Error in (function ()  : 
  clr_obj_ms_convert_to_SEXP: COM variant type code 21 unsupported. Returning NULL

Method:  RDotNet.ProtectedPointer evaluateCall(IntPtr)
Stack trace:
   at RDotNet.Function.evaluateCall(IntPtr call)
   at RDotNet.Function.createCallAndEvaluate(IntPtr argument)
   at Rclr.RDotNetDataConverter.CreateClrObj(Object obj) in c:\Users\hhusl\AppData\Local\Temp\RtmpWMoV35\R.INSTALL337439456109\rClr\src\ClrFacade\RDotNetDataConverter.cs:line 603
   at Rclr.RDotNetDataConverter.TryConvertToSexp(Object obj) in c:\Users\hhusl\AppData\Local\Temp\RtmpWMoV35\R.INSTALL337439456109\rClr\src\ClrFacade\RDotNetDataConverter.cs:line 320
   at Rclr.RDotNetDataConverter.ConvertToR(Object obj) in c:\Users\hhusl\AppData\Local\Temp\RtmpWMoV35\R.INSTALL337439456109\rClr\src\ClrFacade\RDotNetDataConverter.cs:line 220
   at Rclr.ClrFacade.marshallDataToR(Object obj, Boolean tryUseConverter) in c:\Users\hhusl\AppData\Local\Temp\RtmpW
```
I believe this is because RClr (essentially R.NET) doesn't support the type <code>System.UInt64</code>. Could you help me to fix that? Thanks a lot!

**Comment by evolvedmicrobe** [comment]
R has no support for UInt64 data types (it's integer types are restricted to 32 bit).  There have been some attempts to add that in, but nothing that's built in to the default versions of R.  I would avoid UInt64 types, or if you can't, you can try to pass them back and forth as a string with converters as needed.

**Comment by hh1985** [comment]
@evolvedmicrobe Thanks, I will try the way you suggested.
