### ISSUE TITLE
Add facilities reporting the configuration process

### ISSUE THREAD

**Issue by jmp75** [jmp75/rdotnet#4]
what would happen with path discovery, etc.
Purpose clearly to promote first time users to adapt the install/configuration process to the particular of their machine.

**Comment by henrik-ch** [comment]
Hi I think I am getting an issue which is related to this, and I am not sure how to solve it.

I have R installed and I have installed the [F# R Type Provider](http://bluemountaincapital.github.io/FSharpRProvider/) from BlueMountain Capital.

When I try launching this canonic example from [this video](https://www.youtube.com/watch?v=cCuGgA9Yqrs), a stack trace get generated

    // code
    #r @"..\packages\R.NET.Community.1.6.4\lib\net40\RDotNet.dll"
    #r @"..\packages\R.NET.Community.FSharp.1.6.4\lib\net40\RDotNet.FSharp.dll"
    #r @"..\packages\RProvider.1.1.14\lib\net40\RProvider.dll"
    #r @"..\packages\RProvider.1.1.14\lib\net40\RProvider.Runtime.dll"
    #r @"..\packages\FSharp.Data.2.2.5\lib\net40\FSharp.Data.dll"
    
    open System
    open RDotNet
    open RProvider
    open FSharp.Data
    open RProvider.``base``
    open RProvider.graphics
    
    let data = [ for x in 0. .. 0.1 .. 10. -> x * cos x]
    R.plot data


Stack trace:

    > 
    Binding session to 'C:\Users\s5jc8c\SVNRepository\trunk\VisualStudio\fAppforTest\ConsoleApplication1\..\packages\R.NET.Community.1.6.4\lib\net40\RDotNet.dll'...
    Binding session to 'C:\Users\s5jc8c\SVNRepository\trunk\VisualStudio\fAppforTest\ConsoleApplication1\..\packages\RProvider.1.1.14\lib\net40\RProvider.Runtime.dll'...
    System.Exception: Initialization of R.NET failed ---> System.NotSupportedException: R_HOME was not provided and a suitable path could not be found by R.NET
       at RDotNet.NativeLibrary.NativeUtility.SetEnvironmentVariables(String rPath, String rHome)
       at RDotNet.REngine.SetEnvironmentVariables(String rPath, String rHome)
       at RDotNet.REngine.GetInstance(String dll, Boolean initialize, StartupParameter parameter, ICharacterDevice device)
       at RProvider.Internal.RInit.engine@115.Invoke() in c:\Tomas\Public\bmc\FSharp.RProvider\src\RProvider\RInit.fs:line 117
       --- End of inner exception stack trace ---
       at RProvider.Internal.RInit.engine@115.Invoke() in c:\Tomas\Public\bmc\FSharp.RProvider\src\RProvider\RInit.fs:line 125
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.Lazy`1.get_Value()
       at RProvider.RInteropInternal.toR(Object value) in c:\Tomas\Public\bmc\FSharp.RProvider\src\RProvider\RInterop.fs:line 287
       at RProvider.RInterop.passArg@447(List`1 tempSymbols, Object arg) in c:\Tomas\Public\bmc\FSharp.RProvider\src\RProvider\RInterop.fs:line 461
       at RProvider.RInterop.argList@468-1.GenerateNext(IEnumerable`1& next) in c:\Tomas\Public\bmc\FSharp.RProvider\src\RProvider\RInterop.fs:line 469
       at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
       at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
       at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
       at RProvider.RInterop.callFunc(String packageName, String funcName, IEnumerable`1 argsByName, Object[] varArgs) in c:\Tomas\Public\bmc\FSharp.RProvider\src\RProvider\RInterop.fs:line 466
       at <StartupCode$FSI_0004>.$FSI_0004.main@()
    Stopped due to error


Any ideas on what to investigate as a next step would be greatly appreciated.

**Comment by skyguy94** [comment]
Focusing in on the exception text: `R_HOME was not provided and a suitable path could not be found by R.NET`. Do you have R_HOME properly set for your environment?

**Comment by henrik-ch** [comment]
Thank you skyguy94, this was indeed what caused the problem. Setting the R_HOME environment variable resolved the issue.

It's good to note that if you have the R_HOME variable set up incorrectly, the

    open RProvider.``base``

statement shows an error, whereas if you have not setup at all, it doesn't.

**Comment by skyguy94** [comment]
I'm glad it was easy to resolve. I'm clueless about RProvider, so I'm not sure if making sure the error appears when R_HOME is not set is doable.
