### ISSUE TITLE
strange problem using r.net 1.7.0 in Web Host different than Azure

### ISSUE THREAD

**Issue by NorteJoao** [jmp75/rdotnet#93]
I have a ver strange problem using r.net 1.7.0.
Everthing works good in dev Environment and when I deploy to azure app services, but when I deploy to my PROD web Host, we have errors.

Error happen in this line code:
REngine engine = REngine.GetInstance();

The complete code is something like:
```
string rHome = @"[webappPath]\R-3.4.2";
string rPath = Path.Combine(rHome, @"bin\x64");
REngine.SetEnvironmentVariables(rPath, rHome);
REngine engine = REngine.GetInstance();
engine.Initialize();
```
When  SetEnvironmentVariables with two parameters rPath, rHome, I have 502 Erro

If SetEnvironmentVariables with one parameter: rPath the erro has more detail:
System.NullReferenceException: Object reference not set to an instance of an object.
   at RDotNet.NativeLibrary.WindowsRegistryKey.OpenSubKey(String name)
   at RDotNet.NativeLibrary.NativeUtility.GetRCoreRegistryKeyWin32(StringBuilder logger)
   at RDotNet.NativeLibrary.NativeUtility.FindRHome(String rPath, StringBuilder logger)
   at RDotNet.NativeLibrary.NativeUtility.FindRPaths(String& rPath, String& rHome, StringBuilder logSetEnvVar)
   at RDotNet.NativeLibrary.NativeUtility.SetEnvironmentVariables(String rPath, String rHome)
   at RDotNet.REngine.SetEnvironmentVariables(String rPath, String rHome)

R version is R-3.4.4.

There are any idea what is the problem in my Web Host Environment?

Thanks.

**Comment by jmp75** [comment]
Hi,

This is a bit of a hunch but I bumped into a similar issue when I was specifying an R path to R 3.4.4 but the R 3.5.x DLL was loaded. It may be a similar sort of mismatch.

You mention R 3.4.4 but your sample code is `string rHome = @"[webappPath]\R-3.4.2"` so this may be one mismatch.

It is possible to get a more detailed log using `public string FindRPaths(ref string rPath, ref string rHome)`, which may help you.

Last, I happen to just have released version 1.8.1. I am not necessarily advocating upgrading for your case, as I do not see it necessarily helping with your issue, but just letting you know in case you need R 3.5.x support in the future.
