### ISSUE TITLE
Unable to install R packages with R 3.6.0 - messages not displaying correctly

### ISSUE THREAD

**Issue by dannyparsons** [jmp75/rdotnet#99]
In R.NET 1.8.2 I'm finding an issue with installing R packages (in Windows). Specifically, it cannot install a package when the default installation folder (`C:\Users\[Username]\Documents\R\win-library\3.6`) does not yet exist. I'm using 32-bit R in a Windows Form App.

Using the code at the bottom, this works correctly with R 3.4.4. When I run this code and the folder `C:\Users\[Username]\Documents\R\win-library\3.4` does not exist I receive two pop ups one after the other:

![image](https://user-images.githubusercontent.com/11214914/58424621-afd28980-808f-11e9-968f-1411fde65602.png) ![image](https://user-images.githubusercontent.com/11214914/58424625-b3fea700-808f-11e9-9ec1-f2d26b19b175.png)

If I click "yes" to both there is a third pop up to choose the CRAN mirror and then it installs. Below is the Debug output:
```
Warning in install.packages("climatol") :
  'lib = "C:/Program Files/R/R-3.4.4/library"' is not writable
--- Please select a CRAN mirror for use in this session ---
also installing the dependencies 'maps', 'mapdata'

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/maps_3.3.0.zip'
Content type 'application/zip' length 3635230 bytes (3.5 MB)
downloaded 3.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/mapdata_2.3.0.zip'
Content type 'application/zip' length 25640081 bytes (24.5 MB)
downloaded 24.5 MB

trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.4/climatol_3.1.1.zip'
Content type 'application/zip' length 321402 bytes (313 KB)
downloaded 313 KB

package 'maps' successfully unpacked and MD5 sums checked
package 'mapdata' successfully unpacked and MD5 sums checked
package 'climatol' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Danny\AppData\Local\Temp\Rtmp8sLKqE\downloaded_packages
NULL
Loading required package: maps
Loading required package: mapdata
 [1] "climatol"  "mapdata"   "maps"      "stats"     "graphics"  "grDevices"
 [7] "utils"     "datasets"  "methods"   "base"   

```

In R 3.6.0 this produces an exception before any of the pop ups are displayed. If the folder `C:\Users\[Username]\Documents\R\win-library\3.6` already exists then it installs fine. So it seems not being able to display the pop ups is the issues.

I also did this using the R 3.6.0 console directly and the pop up messages were the same as in R 3.4.4 so from the R side I can't see a change in package installation process in 3.6.0.

**Exception details:**
```
RDotNet.EvaluationException
  HResult=0x80131500
  Message=Error in install.packages("climatol") : unable to install packages

  Source=RDotNet
  StackTrace:
   at RDotNet.REngine.Parse(String statement, StringBuilder incompleteStatement, REnvironment environment)
   at RDotNet.REngine.<Defer>d__59.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at RDotNet.REngine.Evaluate(String statement, REnvironment environment)
   at R.Net_Test.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\Danny\source\repos\R.Net-Test\R.Net-Test\Form1.vb:line 15
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```
**Debug output:**
```
Warning in install.packages("climatol") :
  'lib = "C:/Program Files/R/R-3.6.0/library"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) Error in install.packages("climatol") : unable to install packages
In addition: Warning message:
In memory.limit(4095) : cannot decrease memory limit: ignored
Exception thrown: 'RDotNet.EvaluationException' in RDotNet.dll
An unhandled exception of type 'RDotNet.EvaluationException' occurred in RDotNet.dll
Error in install.packages("climatol") : unable to install packages
```

## Test code
```
Imports RDotNet

Public Class Form1

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim engine As REngine

        REngine.SetEnvironmentVariables()
        engine = REngine.GetInstance()
        engine.Initialize()

        engine.AutoPrint = True

        engine.Evaluate("install.packages('climatol')")
        engine.Evaluate("library(climatol)")
    End Sub
End Class
```

**Comment by viebrix** [comment]
It seems to me, that I have read that there is a package installation problem directly in R 3.6.0
Try the next version must be R 3.6.1

See https://cran.r-project.org/bin/windows/base/NEWS.R-3.6.1.html
See https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17556
